apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- team/ingress-api.yaml
- team/deployment.yaml
- team/ingress.yaml
- team/service.yaml
- q1/deployment.yaml
- q1/service.yaml
- q1/ingress.yaml