/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChartSegment: typeof import('./components/ChartSegment.vue')['default']
    ClassShareChart: typeof import('./components/ClassShareChart.vue')['default']
    DataSegment: typeof import('./components/DataSegment.vue')['default']
    ItemsList: typeof import('./components/ItemsList.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    MetricCard: typeof import('./components/MetricCard.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreCard: typeof import('./components/StoreCard.vue')['default']
    TopProductsPieChart: typeof import('./components/TopProductsPieChart.vue')['default']
  }
}
